# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt install clang-format
    - run: sudo apt install python
    - run: curl https://raw.githubusercontent.com/Sarcasm/run-clang-format/master/run-clang-format.py > run-clang-format.py
    - run: sudo chmod +x run-clang-format.py
    - run: ./run-clang-format.py -r .
